config/routes.rb
Hondana::Application.routes.draw do
  resources :books
  resources :bookinfos
  resources :favorite_authors
  get "favorite_authors/update"
  get "favorite_authors/new"
  get "favorite_authors/show"
  resources :members
  resources :sessions, only: [:new, :create, :destroy]
  resources :bookgenres
  resources :password_new

  root to: "top#index"

  match "/members/new", to:  "members#new", via: [ :get, :post, :patch ]
  match "/members/confirm", to:  "members#confirm", via: [ :get, :post, :patch ]
  match "/members/complete", to:  "members#complete", via: [ :get, :post, :patch ]

  match "/notice/", to:  "notice#index", via: [ :get, :post, :patch ]
  match "/notice/read", to:  "notice#read", via: [ :get, :post, :patch ]

  match "/books/new", to:  "books#new", via: [ :get, :post, :patch ]
  match "/books/confirm", to:  "books#confirm", via: [ :get, :post, :patch ]
  match "/books/complete", to:  "books#complete", via: [ :get, :post, :patch ]

  match "/bookinfo_edit/edit/:id", to:  "bookinfo_edit#edit", via: [ :get, :post, :patch ]
  match "/bookinfo_edit/confirm", to:  "bookinfo_edit#confirm", via: [ :get, :post, :patch ]
  match "/bookinfo_edit/complete", to:  "bookinfo_edit#complete", via: [ :get, :post, :patch ]

  match "/bookinfos/new", to:  "bookinfos#new", via: [ :get, :post, :patch ]
  match "/bookinfos/confirm", to:  "bookinfos#confirm", via: [ :get, :post, :patch ]
  match "/bookinfos/complete", to:  "bookinfos#complete", via: [ :get, :post, :patch ]

  match '/signup',  to: 'members#new',          via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match 'top' => 'top#index', via: [ :get, :post, :patch ]
  match 'top/index' => 'top#index', via: [ :get, :post, :patch ]

  match 'user/:id' => 'user#index', via: [ :get, :post, :patch ]

  match 'account' => 'account#index', via: [ :get, :post, :patch ]
  match 'account/index' => 'account#index', via: [ :get, :post, :patch ]
  match 'account/delete' => 'account#delete', via: [ :get, :post, :patch ]
  match 'account/create/:id' => 'account#create', via: [ :get, :post, :patch ]

  match 'account/collection' => 'collection#index', via: [ :get, :post, :patch ]
  match 'account/collection/index' => 'collection#index', via: [ :get, :post, :patch ]
  match 'account/collection/edit/:id' => 'collection#edit', via: [ :get, :post, :patch ]
  match 'account/collection/confirm' => 'collection#confirm', via: [ :get, :post, :patch ]
  match 'account/collection/comp' => 'collection#comp', via: [ :get, :post, :patch ]
  match 'account/collection/delete' => 'collection#delete', via: [ :get, :post, :patch ]
  match 'account/profile' => 'profile#index', via: [ :get, :post, :patch ]
  match 'account/profile/index' => 'profile#index', via: [ :get, :post, :patch ]
  match 'account/profile/edit' => 'profile#edit', via: [ :get, :post, :patch ]
  match 'account/profile/confirm' => 'profile#confirm', via: [ :get, :post, :patch ]
  match 'account/profile/comp' => 'profile#comp', via: [ :get, :post, :patch ]
  match 'account/profile/leave' => 'profire#leave', via: [ :get, :post, :patch ]
  match 'account/profile/leave/index' => 'leave#index', via: [ :get, :post, :patch ]
  match 'account/profile/leave/success' => 'leave#success', via: [ :get, :post, :patch ]

  match 'pw_forget/index' => 'pw_forget#index',via: [ :get, :post, :patch ]
  match 'pw_forget/comp' => 'pw_forget#comp',via: [ :get, :post, :patch ]

  match 'password_new/new' => 'password_new#new',via: [ :get, :post, :patch ]
  match 'password_new/comp' => 'password_new#comp',via: [ :get, :post, :patch ]

  match 'trade' => 'trade#index', via: [ :get, :post, :patch ]
  match 'trade/index' => 'trade#index', via: [ :get, :post, :patch ]

  match 'trade/:id/select' => 'trade#select', via: [ :get, :post, :patch ]
  match 'trade/:id/trade_data' => 'trade#trade_data', via: [ :get, :post, :patch ]
  match 'trade/:idb/confirm' => 'trade#confirm', via: [ :get, :post, :patch ]
  match 'trade/:idb/details' => 'trade#details', via: [ :get, :post, :patch ]
  match 'trade/:idb/comp' => 'trade#comp', via: [ :get, :post, :patch ]
  match 'trade/update2/:tid' => 'trade#update2', via: [ :get, :post, :patch ]
  match 'trade/update3/:tid' => 'trade#update3', via: [ :get, :post, :patch ]
  match 'trade/update4/:tid' => 'trade#update4', via: [ :get, :post, :patch ]

  match 'information/guide' => 'guide#index', via: [ :get, :post, :patch ]
  match 'information/guide/index' => 'guide#index', via: [ :get, :post, :patch ]

  match 'information/fee' => 'fee#index', via: [ :get, :post, :patch ]
  match 'information/fee/index' => 'fee#index', via: [ :get, :post, :patch ]

  match 'information/news' => 'news#index', via: [ :get, :post, :patch ]
  match 'information/news/index' => 'news#index', via: [ :get, :post, :patch ]

  match 'information/terms' => 'terms#index', via: [ :get, :post, :patch ]
  match 'information/terms/index' => 'terms#index', via: [ :get, :post, :patch ]

  match 'information/outline/service' => 'service#index', via: [ :get, :post, :patch ]
  match 'information/outline/service/index' => 'service#index', via: [ :get, :post, :patch ]

  match 'information/outline/corporation' => 'corporation#index', via: [ :get, :post, :patch ]
  match 'information/outline/corporation/index' => 'corporation#index', via: [ :get, :post, :patch ]

  match 'search' => 'search#index', via: [ :get, :post, :patch ]
  match 'search/index' => 'search#index', via: [ :get, :post, :patch ]
  match 'search/details' => 'search#details', via: [ :get, :post, :patch ]
  match 'search/search_details' => 'search#search_details', via: [ :get, :post, :patch ]
  match 'search/:id/details' => 'search#book_details', via: [ :get, :post, :patch ]
  match 'search/addbook' => 'addbook#index', via: [ :get, :post, :patch ]
  match 'search/addbook/index' => 'addbook#index', via: [ :get, :post, :patch ]
  match 'search/addbook/confirm' => 'addbook#confirm', via: [ :get, :post, :patch ]
  match 'search/addbook/comp' => 'addbook#comp', via: [ :get, :post, :patch ]

  match 'support/inquiry' => 'inquiry#index', via: [ :get, :post, :patch ]
  match 'support/inquiry/index' => 'inquiry#index', via: [ :get, :post, :patch ]
  match 'support/inquiry/confirm' => 'inquiry#confirm', via: [ :get, :post, :patch ]
  match 'support/inquiry/comp' => 'inquiry#comp', via: [ :get, :post, :patch ]

end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/shared/_header.html.erb
<% login = 1%>
<div id="head">
	<h1 id="head_image">
		<a href="../../../../top/"><img src="/assets/title_ico.png" alt="「ホンダナ」のトップに移動する" class="button"></a>
	</h1>
	<div id="navigate"><!-- 右ブロック -->
		<p class="box">
			<% if cookies[:id] == nil %>
			<a href="../../../../signin/">
			<% else %>
			<a href="../../../../account/">
			<% end %>
			<img src="/assets/mypage_ico.png" alt="マイページ" class="button"></a></p>
		<p class="box"><a href="../../../../information/outline/service/"><img src="/assets/this_is_ico.png" alt="このサイトについて" class="button"></a></p>
		<div id="head_right">
<header>
  <nav>
	<% if signed_in?%>
      ようこそ <span class="bold"><%= @current_member.nickname %></span> さん<br>
      現在 <span class="bold"><%= @current_member.point %></span> ブク <%#= link_to 'プロフィール変更', edit_member_path(@current_member) %> |
      <%= link_to "ログアウト", signout_path, method: "delete" %><br>

    <% else %>
      <%= link_to "新規会員登録", new_member_path %>
      <%= link_to "ログイン", signin_path %>
    <% end %>
  </nav>
</header>
		</div>

		<!-- 検索バー -->
<%= render 'shared/searchBar' %>
	</div>
</div>
<% if login == 1 %>

<% @notice = Notice.where(members_id: cookies[:id].to_i).order(created_at: :desc) %>
    <% @new_flag = 0 %>
    <% @notice.each do |notice| %>
    <% if notice.read_flag == 0 then %>
       <% @new_flag = 1 %>
     <% end %>
    <% end %>

<!-- ログイン時表示メニュー -->
<div id="member_nav">
	<p><a href="../../../../account/profile/" class="button"><img src="/assets/profile_ico.png" alt="プロフィール"></a></p>
	<p><a href="../../../../trade/" class="button"><img src="/assets/exchange_all_ico.png" alt="交換一覧"></a></p>
	<% if @new_flag == 0 %>
		<p><a href="../../../../notice/" class="button"><img src="/assets/notice_ico.png" alt="会員向け告知"></a></p>
	<% elsif @new_flag == 1 %>
		<p><a href="../../../../notice/" class="button"><img src="/assets/notice_ico_new.png" alt="会員向け告知"></a></p>
	<% else %>
		<p><a href="../../../../notice/" class="button"><img src="/assets/notice_ico.png" alt="会員向け告知"></a></p>
	<% end %>
</div>
<% end %>

app/views/shared/_searchBar.html.erb
<div id="search_bar">
		<%= form_tag :controller => 'search', :action => 'index' do %>
  		<%= text_field_tag 'keyword', session[:keyword] %>
  		<%= submit_tag "検索", :class =>'search_btn' %>
  		<%= link_to '詳細検索', '../../../../search/details' %>
  		<% end %>
</div>